### ISSUE TITLE
running pipenv install failed, do you face this problem? 

### ISSUE THREAD

**Issue by dennis08** [mayuanjason/mbot#1]
Dear Sir,

As you mentioned in jetbot issue, I follow your instrutions, but pipenv install always failed, here is the log, can you give me some advice? 

Thanks so much

`
jetbot@jetbot:~/xtmp/mbot$ pipenv install 
Pipfile.lock (c11c0c) out of date, updating to (021ca8)…
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
searcher: searcher_re:
    0: re.compile('\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jetbot/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1221, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1068, in do_lock
    lockfile=lockfile
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/utils.py", line 649, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/utils.py", line 517, in resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
searcher: searcher_re:
    0: re.compile('\n')

`

**Comment by dennis08** [comment]
> Dear Sir,
> 
> As you mentioned in jetbot issue, I follow your instrutions, but pipenv install always failed, here is the log, can you give me some advice?
> 
> Thanks so much
> 
> `
> jetbot@jetbot:~/xtmp/mbot$ pipenv install
> Pipfile.lock (c11c0c) out of date, updating to (021ca8)…
> Locking [dev-packages] dependencies…
> ✔ Success!
> Locking [packages] dependencies…
> Traceback (most recent call last):
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
> return self.timeout()
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
> raise TIMEOUT(msg)
> pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
> searcher: searcher_re:
> 0: re.compile('\n')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/jetbot/.local/bin/pipenv", line 11, in 
> sys.exit(cli())
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in **call**
> return self.main(*args, **kwargs)
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
> rv = self.invoke(ctx)
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func return ctx.invoke(f, obj, *args, **kwargs) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func return f(get_current_context(), *args, **kwargs) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install editable_packages=state.installstate.editables, File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install keep_outdated=keep_outdated File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1221, in do_init pypi_mirror=pypi_mirror, File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1068, in do_lock lockfile=lockfile File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/utils.py", line 649, in venv_resolve_deps c = resolve(cmd, sp) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/utils.py", line 517, in resolve result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 215, in expect self.subprocess.expect(pattern=pattern, timeout=timeout) File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect timeout, searchwindowsize, async_)
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
> return exp.expect_loop(timeout)
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
> return self.timeout(e)
> File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
> raise TIMEOUT(msg)
> pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
> searcher: searcher_re:
> 0: re.compile('\n')
> <pexpect.popen_spawn.PopenSpawn object at 0x7f95001dd8>
> searcher: searcher_re:
> 0: re.compile('\n')
> 
> `

Dear,

After git pull the newest code, fixed this problem , please ignore last issue.

**Comment by mayuanjason** [comment]
Hi dennis08,

Sorry.
Actually, I don't have a Jetson Nano when I wrote the whole program, so I tested it on my personal computer and seems it can work.

Now, the new Jetson Naon has already shipped to me today and I found some issues run on Jetson Nano, so I will rewrite the whole code and the Wiki this week, please wait...

Anyway, you can test the original program on your Ubuntu PC at first, and of course, you need a camera on your PC.

In original code, I comments some codes in motor.py and robot.py, so if you run the code on Ubuntu PC, you cannot control anything, but you should able to see the Web GUI and the Video on your mobile phone.

You can remove the virtual environment on your Jetson Nano, it should be locate in ~/.local/share/virtualenvs/mbot-xxx

**Comment by mayuanjason** [comment]
Hi dennis08,

BTW, I will rewrite the Wiki in English.

**Comment by dennis08** [comment]
> Hi dennis08,
> 
> BTW, I will rewrite the Wiki in English.

That's great, thanks so much.
After git pull the newest code, this problem had been fixec, please ignore.
