### ISSUE TITLE
mbot2 advanced GUI does not function

### ISSUE THREAD

**Issue by einsteinagogo** [mayuanjason/mbot#3]
mbot runs and functions correctly.

but mbot2 advanced GUI does not.

 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
Traceback (most recent call last):
  File "app.py", line 49, in <module>
    app.run(host='0.0.0.0', port=5000, threaded=True)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/jetbot/mbot/mbot2/app.py'

any ideas...

**Comment by mayuanjason** [comment]
@einsteinagogo 
Sorry for the late reply, very busy these days.
I have fixed the issue, please update the latest code (mbot2/app.py) and try again.

**Comment by einsteinagogo** [comment]
@mayuanjason Thanks that works, just have to remember not to use Chrome, or the Base control does not appear!

Many Thanks

**Comment by mayuanjason** [comment]
Has been solved, close the issue.
